### ISSUE TITLE
Assinar PDF

### ISSUE THREAD

**Issue by sirbig** [rmpt/CCSignature#1]
Boas,

Antes de mais, ótimo trabalho tanto neste projeto como no do CCReader! Está a ajudar muita gente!

Depois de gerar o código Base64 chamando a função Sign como é que posso inserir essa string Base64 como assinatura digital em PDF?

Obrigado.

**Comment by rmpt** [comment]
Olá sirbig,
obrigado pelo comentário, é sempre bom ouvir que tem ajudado.

Sobre adicionar a assinatura a um PDF, a tarefa não é tão simples como parece sem usar libs externas. O que quero dizer é que o processo não passa simplesmente por "inserir a string Base64 como assinatura digital em PDF", é mais do que isso. A assinatura digital do documento implica definir o sítio onde fica a assinatura e usar o conteúdo do próprio documento como base para a assinatura e, para isso, existem já alguma ferramentas. Já usei a lib **iTextSharp** noutros contextos, mas sei que possibilita a assinatura digital de documentos. Pesquise e, se por algum motivo não se conseguir desenrascar, apite que vejo o que consigo fazer.

Rui

**Comment by sirbig** [comment]
Já consegui inserir a assinatura digital em PDF recorrendo ao ITextSharp graças a um exemplo que está num post do forum Portugal-a-Programar onde por acaso o último post é seu com um link para o CCSignature.

A questão que agora coloco é... Qual é a utilidade de possuir uma string Base64 com a assinatura digital do C.C tal como oferece este projeto? Para que fins poderei usar esta mesma string gerada pela DLL?

**Comment by rmpt** [comment]
Os dados assinados em base64 podem ser utilizados para certos serviços de integração. Como talvez nunca os tenha utilizado, não vê a utilidade, mas para quem trabalha em integração de sistemas, como por exemplo alguns serviços do estado, seguradoras etc., muitas das vezes é requerido que o conteúdo assinado seja enviado nos requests para que do outro lado validem a integridade e autenticidade dos dados, esse conteúdo assinado é a string em Base64.

**Comment by sirbig** [comment]
Está esclarecido!
Continue o bom trabalho com estes projetos :)
